cel_interpretor: fix variable name
in python2:
>>> next(i for i in [1,2,3,4]
1
>>> print i
1

in python3:
>>> next(i for i in [1,2,3,4]
1
>>> print(i)
NameError: name 'i' is not defined

so we can't use cel as variable in python3 (anyways we shouldn't have
used cel)